/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sindominio.decodificador_adn.ui;

/**
 *
 * @author julio
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSegundoADN = new javax.swing.JTextField();
        txtPrimerADN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        lineSeparator = new javax.swing.JSeparator();
        btnEncontrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Segundo ADN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 170, 110, 30);

        jLabel2.setText("Primer ADN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 87, 110, 30);
        getContentPane().add(txtSegundoADN);
        txtSegundoADN.setBounds(190, 160, 260, 40);
        getContentPane().add(txtPrimerADN);
        txtPrimerADN.setBounds(190, 90, 260, 40);

        jLabel3.setText("Decodificador De ADN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 20, 530, 40);
        getContentPane().add(lblResultado);
        lblResultado.setBounds(60, 310, 340, 50);

        jLabel4.setText("La Funcion Del Decodificador, es encontrar la cadena de ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 400, 350, 50);

        jLabel5.setText("nucleotidos con mayor longitud entre dos secuencias de ADN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 440, 380, 40);

        btnNuevo.setText("Nuevo");
        getContentPane().add(btnNuevo);
        btnNuevo.setBounds(320, 220, 120, 50);
        getContentPane().add(lineSeparator);
        lineSeparator.setBounds(20, 280, 450, 10);

        btnEncontrar.setText("Encontrar");
        btnEncontrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncontrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEncontrar);
        btnEncontrar.setBounds(180, 220, 120, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncontrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncontrarActionPerformed
        
    }//GEN-LAST:event_btnEncontrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncontrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JSeparator lineSeparator;
    private javax.swing.JTextField txtPrimerADN;
    private javax.swing.JTextField txtSegundoADN;
    // End of variables declaration//GEN-END:variables
}
